-- MySQL Script generated by MySQL Workbench
-- Sat Aug 13 16:29:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Base-ISPC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Base-ISPC` ;

-- -----------------------------------------------------
-- Schema Base-ISPC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base-ISPC` DEFAULT CHARACTER SET utf8 ;
USE `Base-ISPC` ;

-- -----------------------------------------------------
-- Creacion de Tabla `Dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base-ISPC`.`Dueno` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Creacion de Tabla `Perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base-ISPC`.`Perro` (
  `ID_Perro` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha_nac` DATE NULL DEFAULT NULL,
  `Sexo` VARCHAR(45) NULL DEFAULT NULL,
  `DNI_dueno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Perro`),
  INDEX `DNI_idx` (`DNI_dueno` ASC) VISIBLE,
  INDEX `DNI` (`DNI_dueno` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI_dueno`)
    REFERENCES `Base-ISPC`.`Dueno` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Creacion de Tabla `Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base-ISPC`.`Historial` (
  `ID_Historial` INT NOT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Perro` INT NULL DEFAULT NULL,
  `Discripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Monto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Historial`),
  INDEX `ID_Perro_idx` (`Perro` ASC) VISIBLE,
  INDEX `ID_Perro` (`Perro` ASC) VISIBLE,
  CONSTRAINT `ID_Perro`
    FOREIGN KEY (`Perro`)
    REFERENCES `Base-ISPC`.`Perro` (`ID_Perro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insertando datos en las tablas
-- -----------------------------------------------------
INSERT INTO dueno VALUES(14555678, 'Juan Carlos', 'Leiva', '35166889', 'Sabattini 1501' 
);

INSERT INTO perro VALUES(12, 'Boby', 20191203, 'macho', 14555678 
);

UPDATE dueno SET Direccion = 'Libertad 123' WHERE DNI = 14555678;  
